"""Add beer and wine reservation columns to Reservation

Revision ID: ab0976df9fe9
Revises: 9491d634e013
Create Date: 2025-02-09 20:24:56.769068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0976df9fe9'
down_revision = '9491d634e013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beer_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wine_sparkling', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wine_white', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wine_red', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('wine_red')
        batch_op.drop_column('wine_white')
        batch_op.drop_column('wine_sparkling')
        batch_op.drop_column('beer_count')

    # ### end Alembic commands ###
